[tasks.framework_build]
command = "pnpm"
args = ["-C", "../../packages/extension-framework", "build"]


[tasks.framework_live_rebuild]
command = "pnpm"
args = ["-C", "../../packages/extension-framework", "watch"]


[tasks.platform_devserver]
command = "cargo"
args = ["leptos", "watch"]


[tasks.devserver]
run_task = { name = [
	"framework_live_rebuild",
	"platform_devserver",
], parallel = true }
